apiVersion: v1
kind: Namespace
metadata:
  name: openshift-aws-vpce-operator
  labels:
    openshift.io/cluster-monitoring: 'true'
  annotations:
    package-operator.run/phase: namespace
    package-operator.run/collision-protection: IfNoController
