apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-vpce-operator-override-secret
  namespace: openshift-aws-vpce-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
subjects:
- kind: ServiceAccount
  name: aws-vpce-operator
  namespace: openshift-aws-vpce-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-vpce-operator-override-secret
