apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-vpce-operator-override-secret
  namespace: openshift-aws-vpce-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
