apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: aws-vpce-operator
  name: aws-vpce-operator-metrics
  namespace: openshift-aws-vpce-operator
  annotations:
    package-operator.run/phase: deploy
    package-operator.run/collision-protection: IfNoController
spec:
  endpoints:
  - port: http-metrics
  namespaceSelector:
    any: false
    matchNames:
    - openshift-aws-vpce-operator
  selector:
    matchLabels:
      name: aws-vpce-operator
