apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-vpce-operator
  namespace: openshift-aws-vpce-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
