apiVersion: v1
kind: Service
metadata:
  labels:
    name: aws-vpce-operator
  name: aws-vpce-operator-metrics
  namespace: openshift-aws-vpce-operator
  annotations:
    package-operator.run/phase: deploy
    package-operator.run/collision-protection: IfNoController
spec:
  selector:
    name: aws-vpce-operator
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 8080
