apiVersion: v1
kind: Template
parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: IMAGE_DIGEST
  requred: true
- name: REPO_NAME
  value: aws-vpce-operator
  required: true
- name: DISPLAY_NAME
  value: AWS VPCE Operator
  required: true
- name: ENABLE_VPC_ACCEPTANCE  
  value: false
  required: true
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    annotations:
      component-display-name: ${DISPLAY_NAME}
      component-name: ${REPO_NAME}
      telemeter-query: csv_succeeded{_id="$CLUSTER_ID",name=~"${REPO_NAME}.*",exported_namespace=~"openshift-.*",namespace="openshift-operator-lifecycle-manager"} == 1
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: aws-vpce-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
        api.openshift.com/fedramp: 'true'
        api.openshift.com/private-link: 'true'
    resourceApplyMode: Sync
    resources:
    - kind: Namespace
      apiVersion: v1
      metadata:
        name: openshift-aws-vpce-operator
        labels:
          openshift.io/cluster-monitoring: 'true'
    - apiVersion: cloudcredential.openshift.io/v1
      kind: CredentialsRequest
      metadata:
        name: avo-aws-iam-user-creds
        namespace: openshift-${REPO_NAME}
      spec:
        secretRef:
          name: avo-aws-iam-user-creds
          namespace: openshift-${REPO_NAME}
        providerSpec:
          apiVersion: cloudcredential.openshift.io/v1
          kind: AWSProviderSpec
          statementEntries:
          - effect: Allow
            resource: '*'
            action:
            # Extract vpc-id by searching for subnets by tag-key
            - ec2:DescribeSubnets
            # Create and manage security group in specific VPC
            - ec2:CreateSecurityGroup
            - ec2:DeleteSecurityGroup
            - ec2:DescribeSecurityGroups
            # Create and manage security group rules
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:AuthorizeSecurityGroupEgress
            - ec2:DescribeSecurityGroupRules
            # Create and manage a VPC endpoint
            - ec2:CreateVpcEndpoint
            - ec2:DeleteVpcEndpoints
            - ec2:DescribeVpcEndpoints
            - ec2:ModifyVpcEndpoint
            # Create and manage a Route53 Record
            - route53:ChangeResourceRecordSets
            - route53:ListHostedZonesByName
            - route53:ListResourceRecordSets
            # Manage tags and filter based on tags
            - ec2:CreateTags
            - ec2:DeleteTags
            - ec2:DescribeTags
            # VPCEndpointAcceptance
            - sts:AssumeRole
            - ec2:DescribeVpcEndpointConnections
            - ec2:AcceptVpcEndpointConnections
    - kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: aws-vpce-operator
        namespace: openshift-${REPO_NAME}
      subjects:
      - kind: ServiceAccount
        name: aws-vpce-operator
        namespace: openshift-${REPO_NAME}
      roleRef:
        kind: Role
        name: aws-vpce-operator
        namespace: openshift-${REPO_NAME}
        apiGroup: rbac.authorization.k8s.io
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: 'true'
          opsrc-provider: redhat
        name: ${REPO_NAME}-registry
        namespace: openshift-${REPO_NAME}
      spec:
        image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/infra
                  operator: Exists
              weight: 1
        tolerations:
        - operator: Exists
          key: node-role.kubernetes.io/infra
          effect: NoSchedule
        displayName: ${REPO_NAME}
        icon:
          base64data: ''
          mediatype: ''
        publisher: Red Hat
        sourceType: grpc
    - apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: ${REPO_NAME}
        namespace: openshift-${REPO_NAME}
        annotations:
          olm.operatorframework.io/exclude-global-namespace-resolution: 'true'
      spec:
        targetNamespaces:
        - openshift-${REPO_NAME}
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: ${REPO_NAME}
        namespace: openshift-${REPO_NAME}
      spec:
        channel: ${CHANNEL}
        name: ${REPO_NAME}
        source: ${REPO_NAME}-registry
        sourceNamespace: openshift-${REPO_NAME}
    - apiVersion: v1
      data:
        avo_config.yaml: |-
          apiVersion: avo.openshift.io/v1alpha1
          kind: AvoConfig
          enableVpcEndpointController: true
          enableVpcEndpointAcceptanceController: ${ENABLE_VPC_ACCEPTANCE}
      kind: ConfigMap
      metadata:
        name: avo-config
        namespace: openshift-${REPO_NAME}
