apiVersion: v1
kind: Template
metadata:
  name: fr-high-template

parameters:
  - name: PKO_IMAGE
    required: true
  - name: OPERATOR_IMAGE
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: false
  - name: REPO_NAME
    value: aws-vpce-operator
    required: true
  - name: DISPLAY_NAME
    value: AWS VPCE Operator
    required: true
  - name: NAMESPACE
    value: openshift-aws-vpce-operator

objects:
  - apiVersion: package-operator.run/v1alpha1
    kind: ClusterPackage
    metadata:
      name: ${REPO_NAME}
      annotations:
        package-operator.run/collision-protection: IfNoController
    spec:
      image: ${PKO_IMAGE}:${IMAGE_TAG}
      config:
        image: ${OPERATOR_IMAGE}:${IMAGE_TAG}
  - apiVersion: cloudcredential.openshift.io/v1
    kind: CredentialsRequest
    metadata:
      name: avo-aws-iam-user-creds
      namespace: openshift-${REPO_NAME}
    spec:
      secretRef:
         name: avo-aws-iam-user-creds
         namespace: openshift-${REPO_NAME}
      providerSpec:
        apiVersion: cloudcredential.openshift.io/v1
        kind: AWSProviderSpec
        statementEntries:
        - effect: Allow
          resource: '*'
          action:
          # VPCEndpoint Controller
          - ec2:CreateTags
          - ec2:DescribeSubnets
          - ec2:CreateSecurityGroup
          - ec2:DeleteSecurityGroup
          - ec2:DescribeSecurityGroups
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:DescribeSecurityGroupRules
          - ec2:CreateVpcEndpoint
          - ec2:DeleteVpcEndpoints
          - ec2:DescribeVpcEndpoints
          - ec2:DescribeVpcs
          - ec2:ModifyVpcEndpoint
          - ec2:DescribeVpcEndpointServices
          - route53:ChangeResourceRecordSets
          - route53:ListHostedZonesByVPC
          - route53:ListResourceRecordSets
          - route53:ListTagsForResource
          - route53:GetHostedZone
          - route53:CreateHostedZone
          - route53:DeleteHostedZone
          - route53:ChangeTagsForResource
          - route53:CreateVpcAssociationAuthorization
          # VPCEndpointAcceptance Controller
          - sts:AssumeRole
          - ec2:DescribeVpcEndpointConnections
          - ec2:AcceptVpcEndpointConnections
