FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.25-openshift-4.22 AS builder

WORKDIR /build
ENV GOFLAGS=""
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go test ./test/e2e -v -c --tags=osde2e -o /e2e.test

FROM registry.ci.openshift.org/ci/rosa-aws-cli:latest

COPY --from=builder /e2e.test /usr/local/bin/e2e.test
